networks:
  spring_staging_network_jenkins:
    name: spring_staging_network_jenkins
    driver: bridge

services:
  stagingdb:
    image: postgres:15
    container_name: bookdb_staging
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bookdb
    volumes:
      - ./stagingdb:/var/lib/postgresql/data
    ports:
      - "8432:5432"
    networks:
      - spring_staging_network_jenkins
  stagingapi:
    image: "bookapi_api_staging"
    build:
      context: .
      dockerfile: Dockerfile-staging
    container_name: bookapi_staging
    restart: always
    environment:
      - SPRING_DATASOURCE_URL: jdbc:postgresql://stagingdb:5432/bookdb
      - SPRING_DATASOURCE_USERNAME: postgres
      - SPRING_DATASOURCE_PASSWORD: 1234
      - SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8090:8090"
    depends_on:
      - stagingdb
    networks:
      - spring_staging_network_jenkins
volumes:
  pgstagingdb:
    driver: local