networks:
  spring_network_jenkins:
    name: spring_network_jenkins
    driver: bridge

services:
  db:
    image: postgres:15
    container_name: bookdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bookdb
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    ports:
      - "8432:5432"
    networks:
      - spring_network_jenkins
  api:
    build: .
    container_name: bookapi
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8090:8090"
    depends_on:
      - db
    networks:
      - spring_network_jenkins
volumes:
  postgresdb:
    driver: local